
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATG DPOINT LINE NUM POINT PRICE PRODUCT VIRGlista : catgscatgs : catgs catgcatgs : catgcatgs :catg : CATG POINT productsproducts : products productproducts : productproduct : LINE NUM DPOINT PRODUCT DPOINT PRICE DPOINT NUM VIRG'
    
_lr_action_items = {'CATG':([0,2,3,5,7,8,10,18,],[4,4,-3,-2,-5,-7,-6,-8,]),'$end':([0,1,2,3,5,7,8,10,18,],[-4,0,-1,-3,-2,-5,-7,-6,-8,]),'POINT':([4,],[6,]),'LINE':([6,7,8,10,18,],[9,9,-7,-6,-8,]),'NUM':([9,16,],[11,17,]),'DPOINT':([11,13,15,],[12,14,16,]),'PRODUCT':([12,],[13,]),'PRICE':([14,],[15,]),'VIRG':([17,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lista':([0,],[1,]),'catgs':([0,],[2,]),'catg':([0,2,],[3,5,]),'products':([6,],[7,]),'product':([6,7,],[8,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lista","S'",1,None,None,None),
  ('lista -> catgs','lista',1,'p_expression_lista','parser.py',43),
  ('catgs -> catgs catg','catgs',2,'p_expression_catgs','parser.py',48),
  ('catgs -> catg','catgs',1,'p_expression_one_catg','parser.py',52),
  ('catgs -> <empty>','catgs',0,'p_expression_catgs_empty','parser.py',56),
  ('catg -> CATG POINT products','catg',3,'p_expression_catg','parser.py',60),
  ('products -> products product','products',2,'p_expression_products','parser.py',64),
  ('products -> product','products',1,'p_expression_products_one','parser.py',68),
  ('product -> LINE NUM DPOINT PRODUCT DPOINT PRICE DPOINT NUM VIRG','product',9,'p_expression_product','parser.py',72),
]
